# This .yml file is used to specify the conda environment that should be loaded into the RTD instance
name: teqpdocs_ntd2d
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - doxygen
  - cmake
  - pandoc
  - sympy
  - sphinx==7.2.6
  - pip:
    - breathe
    - teqp
    - numpy
    - scipy
    - jupyter
    - notebook
    - nbconvert
    - nbsphinx
    - pandas
    - matplotlib
    - PCSAFTsuperanc
    - sphinxcontrib-doxylink
    - insipid-sphinx-theme
    - CoolProp
