# This .yml file is used to specify the conda environment that should be loaded into the RTD instance
name: teqpdocs_ntd2d
channels:
  - conda-forge
dependencies:
  - pip
  - doxygen
  - cmake
  - pandoc
  - sympy
  - numpy 
  - pandas
  - scipy
  - matplotlib
  - nbconvert
  - sphinx==7.2.6
  - pillow
  - gitpython
  - packaging
  - github-action-utils
  - nbsphinx
  - pip:
    - teqp
    - PCSAFTsuperanc
    - sphinxcontrib-doxylink
    - CoolProp
