name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: checkout submodules
        run: git submodule update --init --recursive
      - uses: usnistgov/NISTtheDocs2Death@main
        with:
          docs-folder: externals/teqp/doc/
          conda-environment: externals/teqp/doc/environment.yml
          pre-build-command: |-
            python prepare_build.py 
          formats: |-
            epub
            pdf
