name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/NISTtheDocs2Death@0.4
        with:
          docs-folder: teqp/doc/
          conda-environment: environment.yml
          pre-build-command: |-
            python prepare_build.py
          formats: |-
            epub
            pdf
