name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: checkout submodules
        run: git submodule update --init --recursive
      - uses: ianhbell/NISTtheDocs2Death@main
        with:
          docs-folder: externals/teqp/doc/
          conda-environment: externals/teqp/doc/environment.yml
          build-pdf-command: 
            rm -rf build/latex && make latexpdf -e && cp build/latex/teqp-docs.pdf build/latex/teqp.pdf
          pre-build-command: 
            python prepare_build.py
          formats: |-
            epub
            pdf
